### ISSUE TITLE
The affray Bugged

### ISSUE THREAD

**Issue by bloodseeker10** [arcemu/arcemu#409] opened 2014-09-27 11:52 UTC
I'm unable to complete the quest cause when i step in the miidle of the crowd the npc "Twiggy Flathead" doesnt announce the start of the fight thus making quest unable to be completed.

**Comment by sanctum32** [comment] 2015-03-30 07:44
This issue was moved to EasyWoW/wotlk-core#5

**Comment by cressidagp** [comment] 2023-05-29 03:02
Hi, this was already reported in  #45

**Comment by dfighter1985** [comment] 2023-05-29 14:47
Yes, but this one is more detailed. I think I will close the other one and track progress here.

**Comment by cressidagp** [comment] 2023-06-03 00:04
Hi there community, in the last week ive has been working on this quest. I scripted in Lua, but it could be rewrited to Python eventually (when APE got more methods). Quest its completable now and with almost all stuff. Im only missing the sheat (weapon at hand) when affray challengers spawn (i will add it later).

Something i noted: there is an AT in the center of the circle (like in all quest were you need to step in some place). Im wondering if i should use AT_SERVER_HOOK instead of a check distance with compare coords.

Twiggy Flathead: [https://pastebin.com/jMPQPHuE](url)
Affray Challengers: [https://pastebin.com/yUPr4Bqz](url)
Big Will: [https://pastebin.com/J6x0MPiG](url)

Also im not 100% sure, but i think Affray Spectators should have random displays id.

**Comment by dfighter1985** [comment] 2023-06-03 12:46
> Something i noted: there is an AT in the center of the circle (like in all quest were you need to step in some place). Im wondering if i should use AT_SERVER_HOOK instead of a check distance with compare coords.
> 

Yes, the areatrigger should be used.
I am also working on this quest in Python, and what I did was use a Quest script for the areatrigger, and implemented a custom script method (that is not yet pushed) to activate Twiggy.

I'll show you a minimal example:
```
def TheAffray_onExploreArea( areaId, player, questId ):
	if areaId != 522:
		return

	mapMgr = player.getMapMgr()	
	announcer = mapMgr.getCreatureNearestCoords( -1686.14, -4323.04, 4.28, 6248 )
	if announcer is not None:
		announcer.activate( player )

arcemu.RegisterQuestEvent( THEAFFRAY_QUEST_ID, arcemu.QUEST_EVENT_ON_EXPLORE_AREA, TheAffray_onExploreArea )

def TwiggyFlathead_onActivate( unit, activator ):
	unit.sendChatMessage( arcemu.CHAT_MSG_MONSTER_SAY, arcemu.LANG_UNIVERSAL, "Wee I'm activated" )
	
arcemu.RegisterUnitEvent( TWIGGY_FLATHEAD_NPC_ID, arcemu.CREATURE_EVENT_ON_ACTIVATE, TwiggyFlathead_onActivate )
```

> 
> Also im not 100% sure, but i think Affray Spectators should have random displays id.
> 

I don't think this matters that much.
If we want it to be 100% like Blizzard's then yes it's important.
However I believe making things work is the most important part, then later you can still improve it.

**Comment by dfighter1985** [comment] 2023-06-04 01:55
@cressidagp Just pushed my version. Check it out! I took your idea of random displayids. I think it will be be fun this way!

**Comment by cressidagp** [comment] 2023-06-04 02:14
..checking... :D

**Comment by cressidagp** [comment] 2023-06-04 03:22
Awesome! and more efficient than that big aiupdate function than i have.
Just a little "cosmeting": big will isnt looking at player, and it should do a roar emote.

Also i was wondering how to handle "all in one variables" in Python. I was trying with a nested dict but maybe that class its the proper way...

**Comment by dfighter1985** [comment] 2023-06-04 12:37
@Tulba @bloodseeker10 what do you guys think about the current version?

**Comment by cressidagp** [comment] 2023-06-04 13:58
Niceee, its more fun with spectators doing emotes.
Got this error on console: 

> at line 30, in TheAffray_onExploreArea
twiggy = mapMgr.getCreatureNearestCoords(...)
Attribute error: NoneType object has no attribute getCreatureNearestCoords

Some feedback:
1. Big Will is not displaying the roar emote and never loose friendly status
2. I saw videos when Challengers run flee on fear before died (handled in ai_agent maybe?)
3. Also saw video when questGiver yell at quest reward: Hail playerName!  New Champion of The Affray!

**Comment by dfighter1985** [comment] 2023-06-04 14:07
> Niceee, its more fun with spectators doing emotes. Got this error on console:
> 
> > at line 30, in TheAffray_onExploreArea
> > twiggy = mapMgr.getCreatureNearestCoords(...)
> > Attribute error: NoneType object has no attribute getCreatureNearestCoords
> 

That could only happen if you are not in the world, but if you can hit the areatrigger you are in world.
So, weird.


> Some feedback:
> 
> 1. Big Will is not displaying the roar emote and never loose friendly status
> 2. I saw videos when Challengers run flee on fear before died (handled in ai_agent maybe?)
> 3. Also saw video when questGiver yell at quest reward: Hail playerName!  New Champion of The Affray!

Are you on the latest Arcemu version? Because I added some methods that are used by the script.

**Comment by cressidagp** [comment] 2023-06-04 14:11
Yes!, will check again, since i died while questing and spawned at cementary... wait a sec

**Comment by cressidagp** [comment] 2023-06-04 14:18
Yeap, still getting console error. Maybe we have different databases? Im using lets call it "ArcDB CommunityEdition" its ArcDB with some fixes than i did while Covid at 2020. But im sure i didnt touch affray npc coords.

**Comment by dfighter1985** [comment] 2023-06-04 14:23
> Yeap, still getting console error. Maybe we have different databases? Im using lets call it "ArcDB CommunityEdition" its ArcDB with some fixes than i did while Covid at 2020. But im sure i didnt touch affray npc coords.

Regardless of the database, a player has a MapMgr, so I don't get it why you are getting that console error.
I will think about it, and see what I can do when I get home.

**Comment by dfighter1985** [comment] 2023-06-04 14:52
@cressidagp had an idea. Are you walking into the areatrigger or teleporting to it?

**Comment by cressidagp** [comment] 2023-06-04 14:58
I use yo port to quest giver, get quest and then walk. But just in case Will do another check.

**Comment by cressidagp** [comment] 2023-06-04 15:02
Yeap, i accept the quest and then get the error message before walk to circle...

**Comment by dfighter1985** [comment] 2023-06-04 15:05
> Yeap, i accept the quest and then get the error message before walk to circle...

This is getting weirder.
Any chance you can make a video of this?

**Comment by cressidagp** [comment] 2023-06-04 15:09
I have that frap addon but never use it. Let me try :D

Also i look at arcemu source code, go to player.cpp in python engine folder, but i cant find getMapMgr method in there...

**Comment by dfighter1985** [comment] 2023-06-04 15:24
> I have that frap addon but never use it. Let me try :D
> 
> Also i look at arcemu source code, go to player.cpp in python engine folder, but i cant find getMapMgr method in there...

It is an ArcPyObject method, so that is not a problem. You would get a different error if the method was missing. The problem is that it returns None for you. Which should not be happening.

**Comment by cressidagp** [comment] 2023-06-04 15:33
Damm its working now...  i think i got it.

Happen when i log in with quest started, then abandon quest, and then got quest again.

My bad, sorry for the waste of time.

**Comment by cressidagp** [comment] 2023-06-04 15:36
I was unable of record a video, loose control of my computer when enable Fraps recording... will look out for another tool for the future.

**Comment by dfighter1985** [comment] 2023-06-04 15:47
> Damm its working now... i think i got it.
> 
> Happen when i log in with quest started, then abandon quest, and then got quest again.
> 
> My bad, sorry for the waste of time.

I'll check when I get home, this shouldn't ever happen.

**Comment by dfighter1985** [comment] 2023-06-04 15:48
> I was unable of record a video, loose control of my computer when enable Fraps recording... will look out for another tool for the future.

Try Obs Studio

**Comment by cressidagp** [comment] 2023-06-04 15:52
I logged close to the house. 

Big Will emote and faction problem persist.

**Comment by dfighter1985** [comment] 2023-06-04 20:57
> Damm its working now... i think i got it.
> 
> Happen when i log in with quest started, then abandon quest, and then got quest again.
> 
> My bad, sorry for the waste of time.

Thanks!
Now I can reproduce it :)

```
[06-04-2023][22:51][Arcemu]WorldSession: Async loading player 36
[06-04-2023][22:51][Arcemu] [DBG] ..\..\src\src\world\Game\Spell\Spell.cpp:902 Spell::prepare Object 0000000000000024 is casting Spell ID 3127 while not in Worl
d
Traceback (most recent call last):
  File "pythonscripts\quest_theaffray.py", line 30, in TheAffray_onExploreArea
    twiggy = mapMgr.getCreatureNearestCoords( -1686.14, -4323.04, 4.28, TWIGGY_FLATHEAD_NPC_ID )
AttributeError: 'NoneType' object has no attribute 'getCreatureNearestCoords'
[06-04-2023][22:51][Arcemu]WorldSession: Fully loading player 36
[06-04-2023][22:51][Arcemu]Login: Player Apoldas logged in.
[06-04-2023][22:51][Arcemu] [DTL] ..\..\src\src\world\PacketHandlers\CharacterHandler.cpp:829 WorldSession::FullLogin WORLD: Created new player for existing pla
yers (Apoldas)
```

...and from the messages I can see that the quest script explore function is somehow called while loading the character.
This is indeed something that is a problem.

**Comment by dfighter1985** [comment] 2023-06-04 21:11
So the problem is that Arcemu calls the Quest script functions when loading the quest log. Which I don't think should be happening.
However I will not change this behavior for now, just because of one quest script.
I will rather just check if None is returned from the getMapMgr() call a bit later.

**Comment by dfighter1985** [comment] 2023-06-04 21:48
> I logged close to the house.
> 
> Big Will emote and faction problem persist.

This is what I see:
https://www.youtube.com/watch?v=WnnwAcVcR8Y

Are you not getting any other console error?

**Comment by cressidagp** [comment] 2023-06-04 22:05
No other errors... maybe its a matter of hardware

**Comment by cressidagp** [comment] 2023-06-04 22:14
Checked again. All working...

**Comment by dfighter1985** [comment] 2023-06-04 22:18
Great! Then I'll close this ticket as fixed :)

**Comment by cressidagp** [comment] 2023-06-04 22:18
Think at some point i use kill command to speed up before the challengers trigger OnEnterCombat :D

**Closed** 2023-06-04 22:18 UTC
