### ISSUE TITLE
playercreateinfo_bars: not all actions are loaded on player creation

### ISSUE THREAD

**Issue by cressidagp** [arcemu/arcemu#429] opened 2020-11-24 16:36 UTC
Greetings, another buggy discovered

How to reproduce: 

create a new character like a Human Rogue... then you will see spell: "Every Man For Himself" not being added to action bars (should be in button "="). This is just one of them, its happen with many spells.

My first thought was this happen because ArcDB has old info... then i decided to manually fill all 120 action bars slots for rogue.
When i check in game most of them are there... but ( 3 ones are missing... including "=" ).

So i decided to write an small SQL script to convert Trinity table to ArcEmu. But then the problem persist.

script writed to convert: 

[tool_playercreateinfo_bars.txt](https://github.com/arcemu/arcemu/files/5603921/tool_playercreateinfo_bars.txt)

table converted (credits to Trinity)

[playercreateinfo_bars.txt](https://github.com/arcemu/arcemu/files/5603922/playercreateinfo_bars.txt)

**Comment by Thetruecrow** [comment] 2021-03-06 07:14
Hello cressidagp, this issue is caused by an incorrect packet structure in SMSG_ACTION_BUTTONS, packet structure should be 8 bits type and 24 bits spellId.
You can see in Player.cpp@4857 where the packet starts, the data is sent as 8 bit type, 16 bits as spellid and 8 bits as misc.

Not really a database issue and more a core support issue.

**Comment by cressidagp** [comment] 2021-03-08 03:02
Hi Karassu, i already realized that this is a core problem, but thank you for the extra info :)

**Comment by dfighter1985** [comment] 2023-05-01 13:38
With the merge of #408 this is now fixed.

**Closed by dfighter1985** 2023-05-01 13:38 UTC
